[build]
builder = "DOCKERFILE"
dockerfilePath = "the-council/backend/Dockerfile"
watchPatterns = ["the-council/backend/**"]

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 15
healthcheckPath = "/api/health"
healthcheckTimeout = 120
